### ISSUE TITLE
[ERR] Test Main Reproducer doesn't work :(

### ISSUE THREAD

**Issue by JustRomeo** [JulienPalard/malloc_stress#1]
Hello, I used your malloc_stress to try my own malloc program. I crash first in the 309 malloc test:
`Can hurt your malloc in 309 steps (0), you can Ctrl-C to see it.`

Then I used the main reproducer "malloc_test" generated by the shell script. So i launch it with my malloc and the seed (which is 38) that make my malloc crashed in the malloc_test.

The malloc_test gave me a main i used, but the main it gives me doesn't crash instead of the malloc_stress ...

**Comment by JulienPalard** [comment]
I just pushed a fix, can you please test it?

**Comment by JustRomeo** [comment]
oh yes, now the realloc function print an error message if the realloc return null. Thank you !
